### ISSUE TITLE
Support normal fights & CHALLENGE_MODE

### ISSUE THREAD

**Issue by b1rdhous3** [kunchenguid/wow-combat-log-parser#3]
Hi, I found your package and it looks very promising to me. 
Is it right, that the focus of your package is focused on Arena Matches?

It seems I can't use the logLine.on Event on other events like spell damage. 
Would it be possible to support log streaming not only on arena (arena_match_started, arena_match_ended) but also on "CHALLENGE_MODE_START" and "CHALLENGE_MODE_END"?
With this it would be possible to use this amazing package also in M+ Dungeons. 

I could also provide a sample log of this or help to implement this, but at the moment I got no real clue where to begin for this.

**Comment by b1rdhous3** [comment]
Just to inform you before you make further investigation. I figured out how to enable the events for CHALLENGE_MODE and I am able to log that Lines.
But I also saw that your module is based on arena and much is missing for PVE Parsing. But I think your module is a good base so I will work in my fork and hopefully I can contribute something. 
I began already :)

**Comment by kunchenguid** [comment]
> Just to inform you before you make further investigation. I figured out how to enable the events for CHALLENGE_MODE and I am able to log that Lines.
> But I also saw that your module is based on arena and much is missing for PVE Parsing. But I think your module is a good base so I will work in my fork and hopefully I can contribute something.
> I began already :)

@b1rdhous3 hi there! you are right that the parser is currently very much optimized for arenas. however from an architecture point of view it's more ideal to have a "base parser" that does nothing else but translating raw logs into structured data, and on top of that we build further modeling of arenas and M+. Please feel free to post your design or early prototypes and we'd be happy to discuss and incorporate changes from you!

**Comment by prsauer** [comment]
@b1rdhous3 going to close this issue as we don't have plans to add support for non-arena modes at the moment. If you have a PR with changes you'd like to see in the baseline parser though we're more than happy to disuss!
